# Generated by Django 5.2.13 on 2026-04-26 04:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('prices', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='price',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='price_photos/'),
        ),
    ]
