# Generated by Django 5.2.13 on 2026-04-27 09:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('items', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='groceryitem',
            name='image_url',
            field=models.URLField(blank=True, default=''),
        ),
    ]
