# Generated by Django 5.2.13 on 2026-05-07 15:57

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('items', '0002_add_image_url_to_groceryitem'),
        ('stores', '0002_add_city_state_to_store'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ScrapingJob',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('state', models.CharField(max_length=100)),
                ('source', models.CharField(choices=[('jiji', 'Jiji.ng'), ('jumia', 'Jumia Nigeria'), ('synthetic', 'Synthetic (NBS Data)')], default='jiji', max_length=20)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('running', 'Running'), ('done', 'Completed'), ('failed', 'Failed')], default='pending', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('started_at', models.DateTimeField(blank=True, null=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('items_found', models.IntegerField(default=0)),
                ('items_imported', models.IntegerField(default=0)),
                ('log_text', models.TextField(blank=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='scraping_jobs', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ScrapedPrice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('raw_item_name', models.CharField(max_length=300)),
                ('raw_store_name', models.CharField(max_length=300)),
                ('raw_price', models.DecimalField(decimal_places=2, max_digits=12)),
                ('raw_city', models.CharField(blank=True, max_length=100)),
                ('source_url', models.URLField(blank=True)),
                ('is_imported', models.BooleanField(default=False)),
                ('scraped_at', models.DateTimeField(auto_now_add=True)),
                ('matched_item', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='scraped_prices', to='items.groceryitem')),
                ('matched_store', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='scraped_prices', to='stores.store')),
                ('job', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='results', to='scraper.scrapingjob')),
            ],
            options={
                'ordering': ['raw_item_name'],
            },
        ),
    ]
